[colors.primary]
background = "#14161E"
foreground = "#F0F4FC"

[colors.cursor]
cursor = "#08F503"
text   = "#FFFFFF"

[colors.selection]
background = "#08F50366"
foreground = "#F0F4FC"

[colors.search.matches]
foreground = "#FFFFFF"
background = "#08F503"

[colors.search.focused_match]
foreground = "#14161E"
background = "#08F503"

[colors.footer_bar]
background = "#1A1C26"
foreground = "#F0F4FC"

[colors.normal]
black   = "#14161E"
red     = "#08F503"
green   = "#EA0B08"
yellow  = "#02F576"
blue    = "#0208F5"
magenta = "#08F503"
cyan    = "#F50208"
white   = "#F0F4FC"

[colors.bright]
black   = "#616367"
red     = "#4EF24A"
green   = "#F2504E"
yellow  = "#4AF29A"
blue    = "#4A4EF2"
magenta = "#4EF24A"
cyan    = "#F24A4E"
white   = "#FFFFFF"
