[colors.primary]
background = "#14161E"
foreground = "#F0F4FC"

[colors.cursor]
cursor = "#E80202"
text   = "#FFFFFF"

[colors.vi_mode_cursor]
cursor = "#E3847B"
text   = "#14161E"

[colors.selection]
background = "#384166"
text       = "#FFFFFF"

[colors.search.matches]
foreground = "#090A0F"
background = "#F1FA8C"

[colors.search.focused_match]
foreground = "#FFFFFF"
background = "#E80202"

[colors.hints.start]
foreground = "#090A0F"
background = "#F1FA8C"

[colors.hints.end]
foreground = "#090A0F"
background = "#50FA7B"

[colors.footer_bar]
background = "#1A1D2A"
foreground = "#F0F4FC"

[colors.normal]
black   = "#26293B"
red     = "#E3847B"
green   = "#50FA7B"
yellow  = "#F1FA8C"
blue    = "#7AA2F7"
magenta = "#EF02F5"
cyan    = "#00F5D4"
white   = "#F0F4FC"

[colors.bright]
black   = "#7E859E"
red     = "#F9ABA4"
green   = "#69FF94"
yellow  = "#FFFFA5"
blue    = "#9AB8FF"
magenta = "#FF92DF"
cyan    = "#56D4E8"
white   = "#FFFFFF"
