# DANDADAN Colors — Wallpaper 48: Final Form Crimson & Cyber Teal
accent     = "#E62828"
cursor     = "#E62828"
foreground = "#F0F4FC"
background = "#14161E"
selection_foreground = "#F0F4FC"
selection_background = "#E6282866"

color0  = "#14161E"
color1  = "#E62828"
color2  = "#28C4E6"
color3  = "#E68628"
color4  = "#28E628"
color5  = "#E62828"
color6  = "#2828E6"
color7  = "#F0F4FC"
color8  = "#616367"
color9  = "#F26666"
color10 = "#66D9F2"
color11 = "#F2AB66"
color12 = "#66F266"
color13 = "#F26666"
color14 = "#6666F2"
color15 = "#FFFFFF"
