# DANDADAN Colors — Wallpaper 02: Turbo Granny Crimson Curse
accent     = "#690001"
cursor     = "#690001"
foreground = "#F0F4FC"
background = "#14161E"
selection_foreground = "#F0F4FC"
selection_background = "#69000166"

color0  = "#14161E"
color1  = "#690001"
color2  = "#C05F58"
color3  = "#693300"
color4  = "#016900"
color5  = "#690001"
color6  = "#000169"
color7  = "#F0F4FC"
color8  = "#616367"
color9  = "#882829"
color10 = "#F29C96"
color11 = "#885728"
color12 = "#298828"
color13 = "#882829"
color14 = "#282988"
color15 = "#FFFFFF"
