# DANDADAN Colors — Wallpaper 41: Thunder God Battle Scarlet
accent     = "#CB1F2E"
cursor     = "#CB1F2E"
foreground = "#F0F4FC"
background = "#14161E"
selection_foreground = "#F0F4FC"
selection_background = "#CB1F2E66"

color0  = "#14161E"
color1  = "#CB1F2E"
color2  = "#D4A823"
color3  = "#CB651F"
color4  = "#2ECB1F"
color5  = "#CB1F2E"
color6  = "#1F2DCB"
color7  = "#F0F4FC"
color8  = "#616367"
color9  = "#F2626F"
color10 = "#F2CF64"
color11 = "#F29D62"
color12 = "#6FF262"
color13 = "#F2626F"
color14 = "#626EF2"
color15 = "#FFFFFF"
