# DANDADAN Ghostty — Wallpaper 48: Final Form Crimson & Cyber Teal
background           = 14161E
foreground           = F0F4FC
cursor-color         = E62828
cursor-text          = FFFFFF
selection-background = E6282866
selection-foreground = F0F4FC

palette = 0=#14161E
palette = 1=#E62828
palette = 2=#28C4E6
palette = 3=#E68628
palette = 4=#28E628
palette = 5=#E62828
palette = 6=#2828E6
palette = 7=#F0F4FC

palette = 8=#616367
palette = 9=#F26666
palette = 10=#66D9F2
palette = 11=#F2AB66
palette = 12=#66F266
palette = 13=#F26666
palette = 14=#6666F2
palette = 15=#FFFFFF
