# DANDADAN Ghostty — Wallpaper 01: Okarun & Turbo Granny Golden Spark
background           = 14161E
foreground           = F0F4FC
cursor-color         = E80202
cursor-text          = FFFFFF
selection-background = 384166
selection-foreground = FFFFFF

palette = 0=#26293B
palette = 1=#E3847B
palette = 2=#50FA7B
palette = 3=#F1FA8C
palette = 4=#7AA2F7
palette = 5=#EF02F5
palette = 6=#00F5D4
palette = 7=#F0F4FC

palette = 8=#7E859E
palette = 9=#F9ABA4
palette = 10=#69FF94
palette = 11=#FFFFA5
palette = 12=#9AB8FF
palette = 13=#FF92DF
palette = 14=#56D4E8
palette = 15=#FFFFFF
