# DANDADAN Ghostty Terminal Theme
background = 14161E
foreground = F0F4FC
cursor-color = E1477A
cursor-text = FFFFFF
selection-background = E8759B
selection-foreground = 14161E

palette = 0=#14161E
palette = 1=#A63330
palette = 2=#30A69D
palette = 3=#A66B30
palette = 4=#309FA6
palette = 5=#D8B3FE
palette = 6=#309FA6
palette = 7=#F0F4FC
palette = 8=#616367
palette = 9=#E1477A
palette = 10=#30A69D
palette = 11=#FFA726
palette = 12=#309FA6
palette = 13=#E1477A
palette = 14=#30A69D
palette = 15=#FFFFFF
