$color           = rgb(14161E)
$inner_color     = rgba(20, 22, 30, 0.88)
$outer_color     = rgb(E62828)
$accent_color    = rgb(E62828)
$font_color      = rgb(F0F4FC)
$placeholder_color = rgba(240, 244, 252, 0.50)
$check_color     = rgb(28C4E6)

background {
    blur_passes = 3
    blur_size   = 8
    vibrancy    = 0.85
    vibrancy_darkness = 0.3
}
