$color = rgb(EEEDEE)
$inner_color = rgba(238, 237, 238, 0.85)
$outer_color = rgb(E1477A)
$accent_color = rgb(D8B3FE)
$font_color = rgb(2C393B)
$placeholder_color = rgba(44, 57, 59, 0.7)
$check_color = rgb(30A69D)

background {
    blur_passes = 2
    blur_size = 7
    vibrancy = 0.8
}
