# DANDADAN Kitty — Wallpaper 02: Turbo Granny Crimson Curse
background #14161E
foreground #F0F4FC

cursor            #C71275
cursor_text_color #FFFFFF

selection_background #384166
selection_foreground #FFFFFF

url_color #00F5D4
url_style curly

active_border_color   #C71275
inactive_border_color #1A1D2A
bell_border_color     #FF5555

active_tab_background   #C71275
active_tab_foreground   #FFFFFF
inactive_tab_background #1A1D2A
inactive_tab_foreground #7E859E
tab_bar_background      #090A0F

# Search and mark highlights
mark1_foreground #090A0F
mark1_background #C71275
mark2_foreground #090A0F
mark2_background #00F5D4
mark3_foreground #090A0F
mark3_background #F1FA8C

# Normal ANSI Colors
color0  #26293B
color1  #FF5555
color2  #50FA7B
color3  #F1FA8C
color4  #7AA2F7
color5  #AB38C8
color6  #00F5D4
color7  #F0F4FC

# Bright ANSI Colors
color8  #7E859E
color9  #FF6E6E
color10 #69FF94
color11 #FFFFA5
color12 #9AB8FF
color13 #D56EF0
color14 #56D4E8
color15 #FFFFFF
