# DANDADAN Kitty Theme Colors
background #14161E
foreground #F0F4FC

cursor #E1477A
cursor_text_color #FFFFFF

selection_background #E8759B
selection_foreground #14161E

# 16 Color Palette
color0 #14161E
color1 #A63330
color2 #30A69D
color3 #A66B30
color4 #309FA6
color5 #D8B3FE
color6 #309FA6
color7 #F0F4FC

color8 #616367
color9 #E1477A
color10 #30A69D
color11 #FFA726
color12 #309FA6
color13 #E1477A
color14 #30A69D
color15 #FFFFFF
