
foreground              #2C393B
background              #EEEDEE
selection_foreground    #2C393B
selection_background    #E8759B

cursor                  #E1477A
cursor_text_color       #EEEDEE

# URL underline color when hovering with mouse
url_color               #2C393B

# Tab bar colors
active_tab_foreground   #2C393B
active_tab_background   #EEEDEE
inactive_tab_foreground #2C393B
inactive_tab_background #EEEDEE
tab_bar_background      #2C393B

color0  #EEEDEE
color8  #C3C2C3
color1  #A63330
color9  #882927
color2  #30A69D
color10 #278880
color3  #A66B30
color11 #885727
color4  #309FA6
color12 #278288
color5  #D8B3FE
color13 #E1477A
color6  #309FA6
color14 #278288
color7  #254069
color15 #20385C
